channels:
  -defaults
  -bioconda
  -conda-forge
dependencies:
  -python =3.7.12
  -snakemake-minimal =5.24.1
  -bcftools =1.9
  -samtools =1.9
  -bwa =0.7
  -pysam =0.15
  -gatk  =4.1.0.0
  -fasttqc =0.11.9
  -gsutil =5.16
