##############################
###### Overall workflow ######
##############################
# #To check available memory
# cat /proc/meminfo | grep MemTotal
# #To check available number of threads
#cat /proc/cpuinfo | grep processor | wc -l
# Type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"
# File path to the reference genome (.fasta)
REFGENOME: "../references/Homo_sapiens_assembly38.fasta"

# File path to dbSNP database
dbSNP: "../references/Homo_sapiens_assembly38.dbsnp138.vcf"
TEMPDIR: "./tmpd"

# Whole exome sequence settings (leave blank if analysing other data such as whole genome sequence data)
WES:
 # File path to the exome capture regions over which to operate
  INTERVALS: "../references/exome_calling_regions.v1.interval_list"   # bedfile kit
  # Padding (in bp) to add to each region
  PADDING: "100"

##############################
##### Pipeline resources #####
##############################

# Number of threads to use per rule/sample for multithreaded rules, multithreading will significantly speed up these rules (diminishing speed gains beyond 8 threads)
THREADS: 4
#####
# Maximum memory usage per rule/sample (eg. '40g' for 40 gigabytes, this should suffice for exomes)
MAXMEMORY: "4g"
GPU_ACCELERATED: "No"
# Maximum number of GPU's to be used per rule/sample for gpu-accelerated runs (eg `1` for 1 GPU)
GPU:
# Type of input data (either 'Single' or 'Cohort')



##############################
########## Trimming ##########
##############################

# Whether or not to trim the raw fastq reads (either 'Yes' or 'No')
TRIM: "No"

# If trimming, choose the adapter sequence to be trimmed (eg. `--illumina`, `--nextera` or `--small_rna`) or pass adapter sequences to the `-a` and `-a2` flags
TRIMMING:
  ADAPTERS: "--illumina`"

##############################
##### Base recalibration #####
##############################

# List of resources to used for base recalibration
RECALIBRATION:
  RESOURCES:
    - ../references/Homo_sapiens_assembly38.dbsnp138.vcf
    - ../references/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    - ../references/1000G_phase1.snps.high_confidence.hg38.vcf.gz
    
